### ISSUE TITLE
Text editor when no trailing line, loses highlighting

### ISSUE THREAD

**Issue by dspivak** [CategoricalData/CQL#18]
When selecting text, if I get to the bottom of the file, the text drops. Adding an empty line fixes this, but it's weird.

**Comment by wisnesky** [comment]
This is tricky to replicate - can you add an example?

**Comment by dspivak** [comment]
Every example of a CQL file I've used has had this issue. Start several
lines above the bottom line. Hold down <shift> and then press the
down-arrow keys—you should see highlighting—until you hit the bottom; when
the highlighting drops for no reason.

**Comment by wisnesky** [comment]
I didn't realize this was about the keyboard.  I was able to replicate and pushed a new jar right now that may have fixed it.

**Comment by dspivak** [comment]
Great!
