### ISSUE TITLE
Tutorial parse error

### ISSUE THREAD

**Issue by Skyfold** [CategoricalData/CQL#32]
How to reproduce:

Open CQL IDE, open Example "Tutorial", hit run, click on "typeside Ty". The Output will be blank and when you click on either "Decide Equation-in-ctx" or "Normalize Term-in-ctx" you will get the error below:

```
org.jparsec.error.ParserException: line 1, column 1:


 **** Possible problem: only identifiers allowed in . notation (lest left-recusion ensue)

 expected, EOF encountered.
```

The relevant code from "Tutorial" is:

```
typeside Ty = literal { 
	java_types
		String = "java.lang.String"
		Integer = "java.lang.Integer"
	java_constants
		String = "return input[0]"
		Integer = "return java.lang.Integer.parseInt(input[0])"
	java_functions
		plus : Integer,Integer -> Integer = "return (input[0] + input[1]).intValue()"
}
```

Given the rest of the Tutorial works correctly I think this might not be a parse error, instead it might be some issue with "Decide Equation-in-ctx" and "Normalize Term-in-ctx".

Regardless this is related to #14.

**Comment by wisnesky** [comment]
That is indeed a peculiar error message.  I pushed a new jar where the decide-eq button does not attempt to parse an equation unless an equal sign in present; that should give better error messages.  I am not sure why that particular error message was chosen for an empty equation.  I also removed the defunct 'normalize-term' button.

**Comment by wisnesky** [comment]
Re-opening because I'm still seeing parse errors on certain examples

**Comment by wisnesky** [comment]
False alarm
