### ISSUE TITLE
CmdLine interface should re-order declarations like the GUI

### ISSUE THREAD

**Issue by wisnesky** [CategoricalData/CQL#42]
The command line interface to CQL does not topologically sort the definitions in the input file before execution, as the GUI executor does.

**Comment by o1lo01ol1o** [comment]
Does one need to order the definitions manually when running the CmdLine then?

**Comment by wisnesky** [comment]
Ah, yes.  The command line interface will use the same declaration order is the input program.  This was by design, to give better control over batch jobs.  However, it should probably be made more apparent.

**Comment by wisnesky** [comment]
the cmd line interface now uses the multi-threaded engine, which re-orders declarations.  we'll be pushing new code shortly
