### ISSUE TITLE
CmdLine logging

### ISSUE THREAD

**Issue by o1lo01ol1o** [CategoricalData/CQL#48]
Is there an option to enable logging to stdout when running via the command line?

**Comment by wisnesky** [comment]
Unfortunately no, in the sense that there’s not even really any logging to print anywhere.  In the viewer partial results show up but, but on the command line your best bet is to track progress with commands, for example, 

command stage1complete = exec_js {
	“any_java_js_nashorn_expression”
	“another expression”
	“1+1” //won’t do much
}

**Comment by o1lo01ol1o** [comment]
N.B. this forces sequential evaluation.
