### ISSUE TITLE
Please review alternate version of CQL IDE Build Instructions

### ISSUE THREAD

**Issue by walambert** [CategoricalData/CQL#62]
Hi there!

When first trying to build the CQL IDE in Eclipse I noticed a few missing steps in the detailed-Eclipse-build-instructions.md wiki file and the brief instructions provided via the CQL github README.md file. Well, it's possible they weren't missing steps but they felt confusing to me, I'm not familiar with building projects in Eclipse.

So, I wrote my own version of the detailed-Eclipse-build-instructions.md wiki file with step-by-step instructions, you can view that version [here](https://github.com/walambert/CQL/wiki/detailed-Eclipse-build-instructions)

It is not possible to submit pull requests to GitHub Wiki repos, that's why I created this ticket. 

If you like the build instructions I wrote, you are welcome to merge them into your version of the detailed-Eclipse-build-instructions.md file :) 

Cheers,
Willa

**Comment by wisnesky** [comment]
That’s awesome.  I’m happy to merge them in, or if you’d like to see to it yourself, I added you as a maintainer.  I think that should let you update the wiki, with that or any other improvements you see fit to add.  Thanks for your help!

**Comment by walambert** [comment]
Hey! Thanks for the add :) 

Yep, that gave me the right permissions to edit the wiki, I pushed my changes and now the detailed-Eclipse-build-instructions.md wiki file reflects those changes!

I'll close this issue with my comment. If I have access to the CQL README.md page I'll drop a direct link to the build-instructions wiki page in that file's "Build and Installation" section

Cheers,
Willa
