### ISSUE TITLE
Java 15 not Java 11

### ISSUE THREAD

**Issue by bond15** [CategoricalData/CQL#66]
Hello

The pre-built jar requires Java 15, not Java 11. Attempting to run with versions of Java less than 15 yields an "incorrect class version" error.

I saw java 11 mentioned in two places:
 README.md 
 and 
 https://categoricaldata.github.io/ 
 
 Thanks for the fun artifact :)

**Comment by wisnesky** [comment]
Changed to java 17 in the GitHub source but seems to be taking a while to update in the browser.
