### ISSUE TITLE
Installation errors when running `java -jar cql.jar`

### ISSUE THREAD

**Issue by zunction** [CategoricalData/CQL#72]
Hi, 

In my attempt to build CQL by running the command above provided in the instructions, I ran into the error below.

```
$ java --version
openjdk 11.0.14.1 2022-02-08
OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.14.1+1 (build 11.0.14.1+1, mixed mode)
$ java -jar cql.jar 
Error: LinkageError occurred while loading main class catdata.ide.IDE
	java.lang.UnsupportedClassVersionError: catdata/ide/IDE has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

Could I get some help?

**Comment by wisnesky** [comment]
Hi there, I think you’re seeing this error because you actually need a more recent JVM than version 11 - I think you need version 15 or higher now.  There’s a few places in the documentation that are stale with respect to JVM version number.

**Comment by zunction** [comment]
Thanks. After digging around the documentation, this worked for me:

1. Download java 17 from [here](https://www.oracle.com/java/technologies/downloads/)
2. The `java -jar cql.jar` command will then run smoothly
